### ISSUE TITLE
More fine grained feature installation

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#1]
At the moment the module only supports installing the full products in the office suite. 
It would be useful to be able so install/upgrade the subcomponents of the products for scenarios where you want to limit the installation footprint.

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
