### ISSUE TITLE
Office 2010 Professional Plus office_product param is incorrect

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#11]
Currently office 2010 pro plus office_product is set to ProPlus where as it should be ProPlusr (additional r)

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
