### ISSUE TITLE
fails on pre-SP2 WinXP because it doesn't have powershell installed.

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#14]
When installing on pre-SP2 Windows XP it fails because it doesn't have powershell installed. Need to add check for powershell or dependency on a module to install it.

**Comment by petems** [comment]
I'd say we can probably close this with XP being so EOL:

Mainstream support ended on April 14, 2009.[4]
Extended support ended on April 8, 2014.[4]
