### ISSUE TITLE
fails on install/upgrade with "failed to check free space on drive"

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#15]
The puppet run errors on Exec['upgrade-office']. When looking into the log it fails with the error: 
    Failed to check free space on drive "" ErrorCode: 3(0x3)

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
