### ISSUE TITLE
dependencies problem

### ISSUE THREAD

**Issue by JanKraljic** [voxpupuli/puppet-msoffice#18]
Error: Could not install module 'liamjbennett-msoffice' (latest: v0.0.2)
  No version of 'joshcooper-powershell' will satisfy dependencies
    'cyberious-pget' (v0.1.3) requires 'joshcooper-powershell' (>= 0.0.6)
    'liamjbennett-msoffice' (v0.0.2) requires 'joshcooper-powershell' (v0.0.4)
    'liamjbennett-windows_firewall' (v0.0.3) requires 'joshcooper-powershell' (>= 0.0.4)

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
