### ISSUE TITLE
support installing office viewers

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#3]
In scenarios when your only installing a partial set of the office products to your clients you often want to also install the available office viewers for the remaining products in the suite.
- Add list of download links to wiki

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
