### ISSUE TITLE
dependencies issues with puppetlabs-powershell

### ISSUE THREAD

**Issue by covidium** [voxpupuli/puppet-msoffice#33]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.7.0
- Ruby: ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
- Distribution: CentOS 7.2.1511
- Module version: ?

### How to reproduce (e.g Puppet code you use)
try to install the puppet-msoffice module with the latest puppetlabs-powershell module installed

### What are you seeing
[root@puppet ~]# puppet module install puppet-msoffice
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'puppet-msoffice' (???)
  No version of 'puppet-msoffice' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module

[root@puppet ~]# puppet module list
/etc/puppetlabs/code/environments/production/modules
├── badgerious-windows_env (v2.2.2)
├── chocolatey-chocolatey (v1.2.6)
├── custom_files (???)
├── puppet-download_file (v2.0.0)
├── puppetlabs-dsc (v1.1.0)
├── puppetlabs-powershell (v2.0.3)                                                                                                                                                           
├── puppetlabs-reboot (v1.2.1)                                                                                                                                                               
└── puppetlabs-stdlib (v4.13.1) 

this module requires:
    puppetlabs/stdlib (>= 3.0.0 <5.0.0)
    puppetlabs/powershell (>= 1.0.0 <2.0.0)
    liamjbennett/win_facts (>= 0.0.1 <1.0.0) 

### What behavior did you expect instead
The module to install

### Output log
not required 

### Any additional information you'd like to impart
Thanks

**Comment by alexjfisher** [comment]
@covidium Thanks for your bug report.  I can't immediately see any reason the module wouldn't work with puppetlabs/powershell 2.x.  Would you be able to test it in your environment by installing with `--ignore-dependencies`?  If all is well, I can update the metadata.json and push a new release in the next couple of days.
