### ISSUE TITLE
Feature request: allow $deplyment_root to be the absolute path to a directory

### ISSUE THREAD

**Issue by marcindulak** [voxpupuli/puppet-msoffice#51]
The module assumes certain directory structure for the Office installation sources.
For example https://github.com/voxpupuli/puppet-msoffice/blob/54baeef77cbf06eb36da3208e8f1af678e55032f/manifests/package.pp#L89 contains:

```
   if $version == '2010' {
     $office_root = "${deployment_root}\\OFFICE${office_num}\\${edition}\\${arch}"
   } else {
     $office_root = "${deployment_root}\\OFFICE${office_num}\\${edition}"
   }
```
In case of installing office from a mounted ISO this path won't work, because one apparently cannot simply copy the contents of a mounted ISO into an arbitrary location (see for example https://answers.microsoft.com/en-us/msoffice/forum/msoffice_other-mso_other/unable-to-install-office-2010-from-dvd-setup/08b6db56-dec7-4164-860a-310f3c1ae7d2). Running `setup.exe` from such location results in "Setup cannot find the required setup controller file".

A workaround when installing from an ISO mount is to set $office_root to the disk of the ISO mount, for example `$office_root = 'd:'`

I'm suggesting `$deployment_root` to become the absolute path to the Office sources directory root (where `setup.exe` is located). In order not to break the current behavior, this could be achieved by introducing a new boolean, e.g. `deployment_root_absolute` which will switch between the current meaning of `$deployment_root` and the proposed one. Something along the lines of https://github.com/marcindulak/puppet-msoffice/commit/1fd0c73a6c7a8b478eff184348a59130060192a2

Related issues:  https://github.com/voxpupuli/puppet-msoffice/issues/50 https://github.com/voxpupuli/puppet-msoffice/issues/9

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.0.0 (from https://downloads.puppetlabs.com/windows/puppet5-nightly/)
- Ruby: 2.3.0
- Module version: https://github.com/voxpupuli/puppet-msoffice/commit/05d4af1c48bc8de5119d3d8f751456a7267240dd

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
