### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by alejandrolidon** [voxpupuli/puppet-msoffice#59]
There is any way to put the license_key after the instalation? I'm using the Office365 and it doesn't give license keys, it Works with internet loggin.

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
