### ISSUE TITLE
Manage desktop and quick launch toolbar shortcuts

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#6]
Manage desktop and quick launch toolbar shortcuts using http://forge.puppetlabs.com/puppetlabs/win_desktop_shortcut

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
