### ISSUE TITLE
support easy tweaking of registry settings

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-msoffice#7]
Manage "HKLM\Software\Microsoft\Office\" and "HKCU\Software\Microsoft\Office\" registry settings. 

Support as many known options as possible.

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
