### ISSUE TITLE
Error when installing Office Home and Business 2010

### ISSUE THREAD

**Issue by Scharfenberg** [voxpupuli/puppet-msoffice#81]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Ruby: 2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]
- Distribution: ???
- Module version: 3.1.2

## How to reproduce (e.g Puppet code you use)

Using a German installation DVD of Office Home and Business 2010 I copied the folder 'x86' from the root directory of the DVD to my harddrive into the folder "C:\Users\User\AppData\Local\Temp\OFFICE14\Home and Business\x86".

Then I execute this puppet code:

```
  msoffice { 'Office 2010':
    ensure          => present,
    version         => '2010',
    edition         => 'Home and Business',
    sp              => '2',
    lang_code       => 'de-de',
    license_key     => $office_license,
    products        => ['Excel'],
    deployment_root => 'C:\\Users\\User\\AppData\\Local\\Temp',
  }
```

## What are you seeing

The following error message occurs during the puppet run:

> Error: '"C:\Users\User\AppData\Local\Temp\OFFICE14\Home and Business\x86\setup.exe" /modify Home and Business /config "C:\Windows\Temp\office_config.xml"' returned 30066 instead of one of [0]
> Error: /Stage[main]/Profile_orchid::Orchid_excel::Install/Msoffice[Office 2010]/Msoffice::Package[microsoft office 2010]/Exec[upgrade-office]/returns: change from 'notrun' to ['0'] failed: '"C:\Users\User\AppData\Local\Temp\OFFICE14\Home and Business\x86\setup.exe" /modify Home and Business /config "C:\Windows\Temp\office_config.xml"' returned 30066 instead of one of [0]

## What behaviour did you expect instead

no error

## Any additional information you'd like to impart

First of all the quotes for the value "Home and Business" of the 'modify' switch are obviously missing. Unfortunately executing the command directly with added quotes does not work either. The error message is different, though (actually the error message above is generated when the quotes are present).

Playing around I've figured out that I need to pass the value "SingleImage" to the 'modify' switch for this command to work. I can find this string in the file 'E:\x86\SingleImage.WW\setup.xml' on my installation DVD (it's the 'Id' attribute of the 'setup' tag).

I conclude that the value for 'office_product' as defined in the params.pp does not work in every case. So I suggest an additional module parameter (e.g. named 'setup_id') that can be used to pass the correct Id.

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
