### ISSUE TITLE
Ruby compatibility issue

### ISSUE THREAD

**Issue by nikhilesh00912** [voxpupuli/puppet-msoffice#88]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.17
- Ruby: 2.4.9
- Distribution:
- Module version: 3.1.2

## How to reproduce (e.g Puppet code you use)
Install puppet 5.5.17, create profile  
  msoffice { 'office 2010':
    version     => '2010',
    edition     => 'Professional Plus',
    sp => '2',
    license_key => '******'
    ensure      => present,
   deployment_root => 'network location'
}
## What are you seeing
Puppet 5.5.17 internally uses ruby version 2.4.9 which doesn't have validate_re syntax. I checked previous tags 3.1.1, 3.1.0 and 3.0.0 all are using validate_re
## Output log
Warning: ModuleLoader: module 'msoffice' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'validate_re'. (file: */*/msoffice/manifests/init.pp, line: 70, column: 3)

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
